name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.3.4
    # ROOT
    - name: Root - Install Dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: .
    - name: Root - Run Build Scripts
      run: yarn build
      working-directory: .
    # WEB
    - name: Web - Install Dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: web
    - name: Web - Check for Lint
      run: yarn lint
    - name: Web - Run Tests
      run: yarn test
    - name: Web - Build Site
      run: yarn build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
