name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    # ROOT
    - name: Root - Check Cache
      uses: actions/cache@v2
      id: root-yarn-cache # use this to check for `cache-hit` (`steps.root-yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-webyarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-webyarn-
    - name: Root - Install Dependencies
      run: yarn install
      with:
        working-directory: .
    - name: Root - Run Build Scripts
      run: yarn build
      working-directory: .
    # WEB
    - name: Web - Check Cache
      uses: actions/cache@v2
      id: web-yarn-cache # use this to check for `cache-hit` (`steps.web-yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: web/.yarn/cache
        key: ${{ runner.os }}-webyarn-${{ hashFiles('web/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-webyarn-
    - name: Web - Install Dependencies
      run: yarn install
    - name: Web - Check for Lint
      run: yarn lint
    - name: Web - Run Tests
      run: yarn test
    - name: Web - Build
      run: yarn build
