name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Set Up Cache
      uses: bahmutov/npm-install@v1
    - name: Install Dependencies
      run: yarn install
    - name: Check for Lint
      run: yarn lint
    - name: Run Tests
      run: yarn test
    - name: Build
      run: yarn build
