name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Web - Set Up Cache
      uses: bahmutov/npm-install@v1
      with:
        working-directory: web
    - name: Web - Install Dependencies
      run: yarn install
    - name: Web - Check for Lint
      run: yarn lint
    - name: Web - Run Tests
      run: yarn test
    - name: Root - Build
      run: yarn build
      working-directory: .
    - name: Web - Build
      run: yarn build
