name: Check PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.3.4
    # ROOT
    - name: Root - Install Dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: .
    - name: Root - Run Build Scripts
      run: yarn build
      working-directory: .
    # WEB
    - name: Web - Install Dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: web
    - name: Web - Check for Lint
      run: yarn lint
    - name: Web - Run Tests
      run: yarn test
    - name: Web - Build
      run: yarn build
